GHA ECS service scale action

diff --git a/.github/workflows/check-compile.yml b/.github/workflows/check-compile.yml
--- a/.github/workflows/check-compile.yml
+++ b/.github/workflows/check-compile.yml
@@ -28,4 +28,7 @@ jobs:
           if ! $(git diff --no-patch --exit-code); then
             echo "Detected uncommitted changes after compiling. Please run 'npm run compile' and commit the changes."
             exit 1
-          fi
+
+      - name: Validate adjust-count usage
+        run: |
+          grep -q "adjust-count" action.yaml index.js || (echo "adjust-count parameter is missing in the action or index.js file" && exit 1)
